import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_hero_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_pages_blocks_rich_text_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_pages_blocks_featured_posts_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_pages_blocks_business_list_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_pages_blocks_event_list_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_pages_blocks_cta_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_pages_blocks_power_prices_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_pages_blocks_weather_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_pages_blocks_flights_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_pages_blocks_nav_jobs_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_pages_blocks_anbud_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_pages_blocks_news_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_pages_blocks_brreg_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_pages_blocks_webcam_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_pages_blocks_currency_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_pages_blocks_holidays_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_pages_blocks_historier_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_pages_blocks_arrangementer_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_pages_blocks_skipstrafikk_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_hero_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_rich_text_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_featured_posts_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_business_list_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_event_list_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_power_prices_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_weather_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_flights_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_nav_jobs_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_anbud_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_news_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_brreg_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_webcam_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_currency_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_holidays_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_historier_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_arrangementer_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_skipstrafikk_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_sidefelt_blocks_hero_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_sidefelt_blocks_rich_text_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_sidefelt_blocks_featured_posts_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_sidefelt_blocks_business_list_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_sidefelt_blocks_event_list_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_sidefelt_blocks_cta_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_sidefelt_blocks_power_prices_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_sidefelt_blocks_weather_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_sidefelt_blocks_flights_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_sidefelt_blocks_nav_jobs_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_sidefelt_blocks_anbud_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_sidefelt_blocks_news_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_sidefelt_blocks_brreg_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_sidefelt_blocks_webcam_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_sidefelt_blocks_currency_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_sidefelt_blocks_holidays_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_sidefelt_blocks_historier_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_sidefelt_blocks_arrangementer_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_sidefelt_blocks_skipstrafikk_bredde" AS ENUM('1', '2', 'full');
  CREATE TYPE "public"."enum_sidefelt_fremhevet_kolonner" AS ENUM('1', '2', '3', '4');
  CREATE TYPE "public"."enum_sidefelt_sidefelt_kolonner" AS ENUM('1', '2', '3', '4');
  CREATE TYPE "public"."enum_sidefelt_midten_kolonner" AS ENUM('1', '2', '3', '4');
  CREATE TYPE "public"."enum_sidefelt_bunn_kolonner" AS ENUM('1', '2', '3', '4');
  ALTER TABLE "pages_blocks_hero" ADD COLUMN "bredde" "enum_pages_blocks_hero_bredde" DEFAULT '1';
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "bredde" "enum_pages_blocks_rich_text_bredde" DEFAULT '1';
  ALTER TABLE "pages_blocks_featured_posts" ADD COLUMN "bredde" "enum_pages_blocks_featured_posts_bredde" DEFAULT '1';
  ALTER TABLE "pages_blocks_business_list" ADD COLUMN "bredde" "enum_pages_blocks_business_list_bredde" DEFAULT '1';
  ALTER TABLE "pages_blocks_event_list" ADD COLUMN "bredde" "enum_pages_blocks_event_list_bredde" DEFAULT '1';
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "bredde" "enum_pages_blocks_cta_bredde" DEFAULT '1';
  ALTER TABLE "pages_blocks_power_prices" ADD COLUMN "bredde" "enum_pages_blocks_power_prices_bredde" DEFAULT '1';
  ALTER TABLE "pages_blocks_weather" ADD COLUMN "bredde" "enum_pages_blocks_weather_bredde" DEFAULT '1';
  ALTER TABLE "pages_blocks_flights" ADD COLUMN "bredde" "enum_pages_blocks_flights_bredde" DEFAULT '1';
  ALTER TABLE "pages_blocks_nav_jobs" ADD COLUMN "bredde" "enum_pages_blocks_nav_jobs_bredde" DEFAULT '1';
  ALTER TABLE "pages_blocks_anbud" ADD COLUMN "bredde" "enum_pages_blocks_anbud_bredde" DEFAULT '1';
  ALTER TABLE "pages_blocks_news" ADD COLUMN "bredde" "enum_pages_blocks_news_bredde" DEFAULT '1';
  ALTER TABLE "pages_blocks_brreg" ADD COLUMN "bredde" "enum_pages_blocks_brreg_bredde" DEFAULT '1';
  ALTER TABLE "pages_blocks_webcam" ADD COLUMN "bredde" "enum_pages_blocks_webcam_bredde" DEFAULT '1';
  ALTER TABLE "pages_blocks_currency" ADD COLUMN "bredde" "enum_pages_blocks_currency_bredde" DEFAULT '1';
  ALTER TABLE "pages_blocks_holidays" ADD COLUMN "bredde" "enum_pages_blocks_holidays_bredde" DEFAULT '1';
  ALTER TABLE "pages_blocks_historier" ADD COLUMN "bredde" "enum_pages_blocks_historier_bredde" DEFAULT '1';
  ALTER TABLE "pages_blocks_arrangementer" ADD COLUMN "bredde" "enum_pages_blocks_arrangementer_bredde" DEFAULT '1';
  ALTER TABLE "pages_blocks_skipstrafikk" ADD COLUMN "bredde" "enum_pages_blocks_skipstrafikk_bredde" DEFAULT '1';
  ALTER TABLE "_pages_v_blocks_hero" ADD COLUMN "bredde" "enum__pages_v_blocks_hero_bredde" DEFAULT '1';
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "bredde" "enum__pages_v_blocks_rich_text_bredde" DEFAULT '1';
  ALTER TABLE "_pages_v_blocks_featured_posts" ADD COLUMN "bredde" "enum__pages_v_blocks_featured_posts_bredde" DEFAULT '1';
  ALTER TABLE "_pages_v_blocks_business_list" ADD COLUMN "bredde" "enum__pages_v_blocks_business_list_bredde" DEFAULT '1';
  ALTER TABLE "_pages_v_blocks_event_list" ADD COLUMN "bredde" "enum__pages_v_blocks_event_list_bredde" DEFAULT '1';
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "bredde" "enum__pages_v_blocks_cta_bredde" DEFAULT '1';
  ALTER TABLE "_pages_v_blocks_power_prices" ADD COLUMN "bredde" "enum__pages_v_blocks_power_prices_bredde" DEFAULT '1';
  ALTER TABLE "_pages_v_blocks_weather" ADD COLUMN "bredde" "enum__pages_v_blocks_weather_bredde" DEFAULT '1';
  ALTER TABLE "_pages_v_blocks_flights" ADD COLUMN "bredde" "enum__pages_v_blocks_flights_bredde" DEFAULT '1';
  ALTER TABLE "_pages_v_blocks_nav_jobs" ADD COLUMN "bredde" "enum__pages_v_blocks_nav_jobs_bredde" DEFAULT '1';
  ALTER TABLE "_pages_v_blocks_anbud" ADD COLUMN "bredde" "enum__pages_v_blocks_anbud_bredde" DEFAULT '1';
  ALTER TABLE "_pages_v_blocks_news" ADD COLUMN "bredde" "enum__pages_v_blocks_news_bredde" DEFAULT '1';
  ALTER TABLE "_pages_v_blocks_brreg" ADD COLUMN "bredde" "enum__pages_v_blocks_brreg_bredde" DEFAULT '1';
  ALTER TABLE "_pages_v_blocks_webcam" ADD COLUMN "bredde" "enum__pages_v_blocks_webcam_bredde" DEFAULT '1';
  ALTER TABLE "_pages_v_blocks_currency" ADD COLUMN "bredde" "enum__pages_v_blocks_currency_bredde" DEFAULT '1';
  ALTER TABLE "_pages_v_blocks_holidays" ADD COLUMN "bredde" "enum__pages_v_blocks_holidays_bredde" DEFAULT '1';
  ALTER TABLE "_pages_v_blocks_historier" ADD COLUMN "bredde" "enum__pages_v_blocks_historier_bredde" DEFAULT '1';
  ALTER TABLE "_pages_v_blocks_arrangementer" ADD COLUMN "bredde" "enum__pages_v_blocks_arrangementer_bredde" DEFAULT '1';
  ALTER TABLE "_pages_v_blocks_skipstrafikk" ADD COLUMN "bredde" "enum__pages_v_blocks_skipstrafikk_bredde" DEFAULT '1';
  ALTER TABLE "sidefelt_blocks_hero" ADD COLUMN "bredde" "enum_sidefelt_blocks_hero_bredde" DEFAULT '1';
  ALTER TABLE "sidefelt_blocks_rich_text" ADD COLUMN "bredde" "enum_sidefelt_blocks_rich_text_bredde" DEFAULT '1';
  ALTER TABLE "sidefelt_blocks_featured_posts" ADD COLUMN "bredde" "enum_sidefelt_blocks_featured_posts_bredde" DEFAULT '1';
  ALTER TABLE "sidefelt_blocks_business_list" ADD COLUMN "bredde" "enum_sidefelt_blocks_business_list_bredde" DEFAULT '1';
  ALTER TABLE "sidefelt_blocks_event_list" ADD COLUMN "bredde" "enum_sidefelt_blocks_event_list_bredde" DEFAULT '1';
  ALTER TABLE "sidefelt_blocks_cta" ADD COLUMN "bredde" "enum_sidefelt_blocks_cta_bredde" DEFAULT '1';
  ALTER TABLE "sidefelt_blocks_power_prices" ADD COLUMN "bredde" "enum_sidefelt_blocks_power_prices_bredde" DEFAULT '1';
  ALTER TABLE "sidefelt_blocks_weather" ADD COLUMN "bredde" "enum_sidefelt_blocks_weather_bredde" DEFAULT '1';
  ALTER TABLE "sidefelt_blocks_flights" ADD COLUMN "bredde" "enum_sidefelt_blocks_flights_bredde" DEFAULT '1';
  ALTER TABLE "sidefelt_blocks_nav_jobs" ADD COLUMN "bredde" "enum_sidefelt_blocks_nav_jobs_bredde" DEFAULT '1';
  ALTER TABLE "sidefelt_blocks_anbud" ADD COLUMN "bredde" "enum_sidefelt_blocks_anbud_bredde" DEFAULT '1';
  ALTER TABLE "sidefelt_blocks_news" ADD COLUMN "bredde" "enum_sidefelt_blocks_news_bredde" DEFAULT '1';
  ALTER TABLE "sidefelt_blocks_brreg" ADD COLUMN "bredde" "enum_sidefelt_blocks_brreg_bredde" DEFAULT '1';
  ALTER TABLE "sidefelt_blocks_webcam" ADD COLUMN "bredde" "enum_sidefelt_blocks_webcam_bredde" DEFAULT '1';
  ALTER TABLE "sidefelt_blocks_currency" ADD COLUMN "bredde" "enum_sidefelt_blocks_currency_bredde" DEFAULT '1';
  ALTER TABLE "sidefelt_blocks_holidays" ADD COLUMN "bredde" "enum_sidefelt_blocks_holidays_bredde" DEFAULT '1';
  ALTER TABLE "sidefelt_blocks_historier" ADD COLUMN "bredde" "enum_sidefelt_blocks_historier_bredde" DEFAULT '1';
  ALTER TABLE "sidefelt_blocks_arrangementer" ADD COLUMN "bredde" "enum_sidefelt_blocks_arrangementer_bredde" DEFAULT '1';
  ALTER TABLE "sidefelt_blocks_skipstrafikk" ADD COLUMN "bredde" "enum_sidefelt_blocks_skipstrafikk_bredde" DEFAULT '1';
  ALTER TABLE "sidefelt" ADD COLUMN "fremhevet_kolonner" "enum_sidefelt_fremhevet_kolonner" DEFAULT '1';
  ALTER TABLE "sidefelt" ADD COLUMN "sidefelt_kolonner" "enum_sidefelt_sidefelt_kolonner" DEFAULT '1';
  ALTER TABLE "sidefelt" ADD COLUMN "midten_kolonner" "enum_sidefelt_midten_kolonner" DEFAULT '2';
  ALTER TABLE "sidefelt" ADD COLUMN "bunn_kolonner" "enum_sidefelt_bunn_kolonner" DEFAULT '3';`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_hero" DROP COLUMN "bredde";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "bredde";
  ALTER TABLE "pages_blocks_featured_posts" DROP COLUMN "bredde";
  ALTER TABLE "pages_blocks_business_list" DROP COLUMN "bredde";
  ALTER TABLE "pages_blocks_event_list" DROP COLUMN "bredde";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "bredde";
  ALTER TABLE "pages_blocks_power_prices" DROP COLUMN "bredde";
  ALTER TABLE "pages_blocks_weather" DROP COLUMN "bredde";
  ALTER TABLE "pages_blocks_flights" DROP COLUMN "bredde";
  ALTER TABLE "pages_blocks_nav_jobs" DROP COLUMN "bredde";
  ALTER TABLE "pages_blocks_anbud" DROP COLUMN "bredde";
  ALTER TABLE "pages_blocks_news" DROP COLUMN "bredde";
  ALTER TABLE "pages_blocks_brreg" DROP COLUMN "bredde";
  ALTER TABLE "pages_blocks_webcam" DROP COLUMN "bredde";
  ALTER TABLE "pages_blocks_currency" DROP COLUMN "bredde";
  ALTER TABLE "pages_blocks_holidays" DROP COLUMN "bredde";
  ALTER TABLE "pages_blocks_historier" DROP COLUMN "bredde";
  ALTER TABLE "pages_blocks_arrangementer" DROP COLUMN "bredde";
  ALTER TABLE "pages_blocks_skipstrafikk" DROP COLUMN "bredde";
  ALTER TABLE "_pages_v_blocks_hero" DROP COLUMN "bredde";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "bredde";
  ALTER TABLE "_pages_v_blocks_featured_posts" DROP COLUMN "bredde";
  ALTER TABLE "_pages_v_blocks_business_list" DROP COLUMN "bredde";
  ALTER TABLE "_pages_v_blocks_event_list" DROP COLUMN "bredde";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "bredde";
  ALTER TABLE "_pages_v_blocks_power_prices" DROP COLUMN "bredde";
  ALTER TABLE "_pages_v_blocks_weather" DROP COLUMN "bredde";
  ALTER TABLE "_pages_v_blocks_flights" DROP COLUMN "bredde";
  ALTER TABLE "_pages_v_blocks_nav_jobs" DROP COLUMN "bredde";
  ALTER TABLE "_pages_v_blocks_anbud" DROP COLUMN "bredde";
  ALTER TABLE "_pages_v_blocks_news" DROP COLUMN "bredde";
  ALTER TABLE "_pages_v_blocks_brreg" DROP COLUMN "bredde";
  ALTER TABLE "_pages_v_blocks_webcam" DROP COLUMN "bredde";
  ALTER TABLE "_pages_v_blocks_currency" DROP COLUMN "bredde";
  ALTER TABLE "_pages_v_blocks_holidays" DROP COLUMN "bredde";
  ALTER TABLE "_pages_v_blocks_historier" DROP COLUMN "bredde";
  ALTER TABLE "_pages_v_blocks_arrangementer" DROP COLUMN "bredde";
  ALTER TABLE "_pages_v_blocks_skipstrafikk" DROP COLUMN "bredde";
  ALTER TABLE "sidefelt_blocks_hero" DROP COLUMN "bredde";
  ALTER TABLE "sidefelt_blocks_rich_text" DROP COLUMN "bredde";
  ALTER TABLE "sidefelt_blocks_featured_posts" DROP COLUMN "bredde";
  ALTER TABLE "sidefelt_blocks_business_list" DROP COLUMN "bredde";
  ALTER TABLE "sidefelt_blocks_event_list" DROP COLUMN "bredde";
  ALTER TABLE "sidefelt_blocks_cta" DROP COLUMN "bredde";
  ALTER TABLE "sidefelt_blocks_power_prices" DROP COLUMN "bredde";
  ALTER TABLE "sidefelt_blocks_weather" DROP COLUMN "bredde";
  ALTER TABLE "sidefelt_blocks_flights" DROP COLUMN "bredde";
  ALTER TABLE "sidefelt_blocks_nav_jobs" DROP COLUMN "bredde";
  ALTER TABLE "sidefelt_blocks_anbud" DROP COLUMN "bredde";
  ALTER TABLE "sidefelt_blocks_news" DROP COLUMN "bredde";
  ALTER TABLE "sidefelt_blocks_brreg" DROP COLUMN "bredde";
  ALTER TABLE "sidefelt_blocks_webcam" DROP COLUMN "bredde";
  ALTER TABLE "sidefelt_blocks_currency" DROP COLUMN "bredde";
  ALTER TABLE "sidefelt_blocks_holidays" DROP COLUMN "bredde";
  ALTER TABLE "sidefelt_blocks_historier" DROP COLUMN "bredde";
  ALTER TABLE "sidefelt_blocks_arrangementer" DROP COLUMN "bredde";
  ALTER TABLE "sidefelt_blocks_skipstrafikk" DROP COLUMN "bredde";
  ALTER TABLE "sidefelt" DROP COLUMN "fremhevet_kolonner";
  ALTER TABLE "sidefelt" DROP COLUMN "sidefelt_kolonner";
  ALTER TABLE "sidefelt" DROP COLUMN "midten_kolonner";
  ALTER TABLE "sidefelt" DROP COLUMN "bunn_kolonner";
  DROP TYPE "public"."enum_pages_blocks_hero_bredde";
  DROP TYPE "public"."enum_pages_blocks_rich_text_bredde";
  DROP TYPE "public"."enum_pages_blocks_featured_posts_bredde";
  DROP TYPE "public"."enum_pages_blocks_business_list_bredde";
  DROP TYPE "public"."enum_pages_blocks_event_list_bredde";
  DROP TYPE "public"."enum_pages_blocks_cta_bredde";
  DROP TYPE "public"."enum_pages_blocks_power_prices_bredde";
  DROP TYPE "public"."enum_pages_blocks_weather_bredde";
  DROP TYPE "public"."enum_pages_blocks_flights_bredde";
  DROP TYPE "public"."enum_pages_blocks_nav_jobs_bredde";
  DROP TYPE "public"."enum_pages_blocks_anbud_bredde";
  DROP TYPE "public"."enum_pages_blocks_news_bredde";
  DROP TYPE "public"."enum_pages_blocks_brreg_bredde";
  DROP TYPE "public"."enum_pages_blocks_webcam_bredde";
  DROP TYPE "public"."enum_pages_blocks_currency_bredde";
  DROP TYPE "public"."enum_pages_blocks_holidays_bredde";
  DROP TYPE "public"."enum_pages_blocks_historier_bredde";
  DROP TYPE "public"."enum_pages_blocks_arrangementer_bredde";
  DROP TYPE "public"."enum_pages_blocks_skipstrafikk_bredde";
  DROP TYPE "public"."enum__pages_v_blocks_hero_bredde";
  DROP TYPE "public"."enum__pages_v_blocks_rich_text_bredde";
  DROP TYPE "public"."enum__pages_v_blocks_featured_posts_bredde";
  DROP TYPE "public"."enum__pages_v_blocks_business_list_bredde";
  DROP TYPE "public"."enum__pages_v_blocks_event_list_bredde";
  DROP TYPE "public"."enum__pages_v_blocks_cta_bredde";
  DROP TYPE "public"."enum__pages_v_blocks_power_prices_bredde";
  DROP TYPE "public"."enum__pages_v_blocks_weather_bredde";
  DROP TYPE "public"."enum__pages_v_blocks_flights_bredde";
  DROP TYPE "public"."enum__pages_v_blocks_nav_jobs_bredde";
  DROP TYPE "public"."enum__pages_v_blocks_anbud_bredde";
  DROP TYPE "public"."enum__pages_v_blocks_news_bredde";
  DROP TYPE "public"."enum__pages_v_blocks_brreg_bredde";
  DROP TYPE "public"."enum__pages_v_blocks_webcam_bredde";
  DROP TYPE "public"."enum__pages_v_blocks_currency_bredde";
  DROP TYPE "public"."enum__pages_v_blocks_holidays_bredde";
  DROP TYPE "public"."enum__pages_v_blocks_historier_bredde";
  DROP TYPE "public"."enum__pages_v_blocks_arrangementer_bredde";
  DROP TYPE "public"."enum__pages_v_blocks_skipstrafikk_bredde";
  DROP TYPE "public"."enum_sidefelt_blocks_hero_bredde";
  DROP TYPE "public"."enum_sidefelt_blocks_rich_text_bredde";
  DROP TYPE "public"."enum_sidefelt_blocks_featured_posts_bredde";
  DROP TYPE "public"."enum_sidefelt_blocks_business_list_bredde";
  DROP TYPE "public"."enum_sidefelt_blocks_event_list_bredde";
  DROP TYPE "public"."enum_sidefelt_blocks_cta_bredde";
  DROP TYPE "public"."enum_sidefelt_blocks_power_prices_bredde";
  DROP TYPE "public"."enum_sidefelt_blocks_weather_bredde";
  DROP TYPE "public"."enum_sidefelt_blocks_flights_bredde";
  DROP TYPE "public"."enum_sidefelt_blocks_nav_jobs_bredde";
  DROP TYPE "public"."enum_sidefelt_blocks_anbud_bredde";
  DROP TYPE "public"."enum_sidefelt_blocks_news_bredde";
  DROP TYPE "public"."enum_sidefelt_blocks_brreg_bredde";
  DROP TYPE "public"."enum_sidefelt_blocks_webcam_bredde";
  DROP TYPE "public"."enum_sidefelt_blocks_currency_bredde";
  DROP TYPE "public"."enum_sidefelt_blocks_holidays_bredde";
  DROP TYPE "public"."enum_sidefelt_blocks_historier_bredde";
  DROP TYPE "public"."enum_sidefelt_blocks_arrangementer_bredde";
  DROP TYPE "public"."enum_sidefelt_blocks_skipstrafikk_bredde";
  DROP TYPE "public"."enum_sidefelt_fremhevet_kolonner";
  DROP TYPE "public"."enum_sidefelt_sidefelt_kolonner";
  DROP TYPE "public"."enum_sidefelt_midten_kolonner";
  DROP TYPE "public"."enum_sidefelt_bunn_kolonner";`)
}
