/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    members: MemberAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    places: Place;
    posts: Post;
    businesses: Business;
    events: Event;
    jobs: Job;
    'press-releases': PressRelease;
    newsletters: Newsletter;
    ads: Ad;
    pages: Page;
    members: Member;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    places: PlacesSelect<false> | PlacesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    businesses: BusinessesSelect<false> | BusinessesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'press-releases': PressReleasesSelect<false> | PressReleasesSelect<true>;
    newsletters: NewslettersSelect<false> | NewslettersSelect<true>;
    ads: AdsSelect<false> | AdsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    hero: Hero;
    header: Header;
    footer: Footer;
    sidefelt: Sidefelt;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    sidefelt: SidefeltSelect<false> | SidefeltSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Member;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface MemberAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  roles: ('admin' | 'editor' | 'author')[];
  /**
   * Kort presentasjon, vises ved artikler.
   */
  bio?: string | null;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Beskrivelse av bildet (viktig for SEO og universell utforming).
   */
  alt: string;
  /**
   * Valgfri bildetekst.
   */
  caption?: string | null;
  /**
   * Fotograf / kilde.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * URL-vennlig identifikator. Genereres automatisk hvis tom.
   */
  slug?: string | null;
  /**
   * Kort beskrivelse, kan vises på kategoriside.
   */
  description?: string | null;
  /**
   * Valgfri hex-farge for visuell merking (f.eks. #1f6feb).
   */
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places".
 */
export interface Place {
  id: number;
  name: string;
  /**
   * URL-vennlig identifikator. Genereres automatisk hvis tom.
   */
  slug?: string | null;
  municipality?: string | null;
  lat?: number | null;
  lng?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  submittedBy?: (number | null) | Member;
  title: string;
  /**
   * Kort sammendrag som vises i lister og søk.
   */
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedBusinesses?: (number | Business)[] | null;
  relatedEvents?: (number | Event)[] | null;
  /**
   * URL-vennlig identifikator. Genereres automatisk hvis tom.
   */
  slug?: string | null;
  category?: (number | null) | Category;
  place?: (number | null) | Place;
  author?: (number | null) | User;
  tags?: string[] | null;
  /**
   * Vis på forsiden.
   */
  featured?: boolean | null;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  name?: string | null;
  avatar?: (number | null) | Media;
  bio?: string | null;
  memberType?: ('person' | 'org') | null;
  /**
   * Hukes av av stab.
   */
  approved?: boolean | null;
  sub?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'members';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses".
 */
export interface Business {
  id: number;
  name: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  address?: string | null;
  city?: string | null;
  county?: string | null;
  country?: string | null;
  /**
   * Fylles ut automatisk fra By/Fylke/Land
   */
  lat?: number | null;
  /**
   * Fylles ut automatisk fra By/Fylke/Land
   */
  lng?: number | null;
  openingHours?:
    | {
        day: 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun';
        opens?: string | null;
        closes?: string | null;
        id?: string | null;
      }[]
    | null;
  social?: {
    facebook?: string | null;
    instagram?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * URL-vennlig identifikator. Genereres automatisk hvis tom.
   */
  slug?: string | null;
  submittedBy?: (number | null) | Member;
  category?: (number | null) | Category;
  place?: (number | null) | Place;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  submittedBy?: (number | null) | Member;
  title: string;
  image?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  startDate: string;
  endDate?: string | null;
  locationName?: string | null;
  organizer?: (number | null) | Business;
  ticketUrl?: string | null;
  free?: boolean | null;
  price?: string | null;
  /**
   * URL-vennlig identifikator. Genereres automatisk hvis tom.
   */
  slug?: string | null;
  category?: (number | null) | Category;
  place?: (number | null) | Place;
  featured?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  submittedBy?: (number | null) | Member;
  title: string;
  employer: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  jobType?: ('full-time' | 'part-time' | 'temp' | 'contract' | 'seasonal' | 'apprentice') | null;
  deadline?: string | null;
  locationName?: string | null;
  applicationUrl?: string | null;
  applicationEmail?: string | null;
  contactName?: string | null;
  contactPhone?: string | null;
  /**
   * URL-vennlig identifikator. Genereres automatisk hvis tom.
   */
  slug?: string | null;
  place?: (number | null) | Place;
  category?: (number | null) | Category;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-releases".
 */
export interface PressRelease {
  id: number;
  title: string;
  organization?: string | null;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image?: (number | null) | Media;
  contactName?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  /**
   * URL-vennlig identifikator. Genereres automatisk hvis tom.
   */
  slug?: string | null;
  submittedBy?: (number | null) | Member;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters".
 */
export interface Newsletter {
  id: number;
  title: string;
  organization?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image?: (number | null) | Media;
  /**
   * URL-vennlig identifikator. Genereres automatisk hvis tom.
   */
  slug?: string | null;
  submittedBy?: (number | null) | Member;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ads".
 */
export interface Ad {
  id: number;
  title: string;
  advertiser?: string | null;
  image: number | Media;
  linkUrl: string;
  placement: 'header' | 'sidebar' | 'in-content' | 'footer';
  startDate?: string | null;
  endDate?: string | null;
  active?: boolean | null;
  impressions?: number | null;
  clicks?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL-vennlig identifikator. Genereres automatisk hvis tom.
   */
  slug?: string | null;
  /**
   * Bygg siden ved å stable blokker i ønsket rekkefølge.
   */
  layout?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            image?: (number | null) | Media;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            heading?: string | null;
            posts?: (number | Post)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredPosts';
          }
        | {
            heading?: string | null;
            category?: (number | null) | Category;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'businessList';
          }
        | {
            heading?: string | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'eventList';
          }
        | {
            heading: string;
            text?: string | null;
            buttonLabel?: string | null;
            buttonUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            title?: string | null;
            zone?: ('NO1' | 'NO2' | 'NO3' | 'NO4' | 'NO5') | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'powerPrices';
          }
        | {
            title?: string | null;
            /**
             * La stå tomt for standard Helgeland-steder (Brønnøysund, Sandnessjøen, Mosjøen, Mo i Rana).
             */
            locations?:
              | {
                  name: string;
                  lat: number;
                  lon: number;
                  id?: string | null;
                }[]
              | null;
            /**
             * 1–7 dager.
             */
            days?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'weather';
          }
        | {
            title?: string | null;
            airports?: ('BNN' | 'SSJ' | 'MJF')[] | null;
            direction?: ('departure' | 'arrival' | 'begge') | null;
            /**
             * 1–10 avganger per flyplass.
             */
            count?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'flights';
          }
        | {
            title?: string | null;
            /**
             * 1–20 stillinger fra NAV Arbeidsplassen.
             */
            count?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'navJobs';
          }
        | {
            title?: string | null;
            /**
             * La stå tomt for alle fire kilder.
             */
            sources?: ('BAnett' | 'Helgelendingen' | 'Helgelands Blad' | 'NRK Nordland')[] | null;
            count?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'news';
          }
        | {
            title?: string | null;
            count?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'brreg';
          }
        | {
            title?: string | null;
            /**
             * La stå tomt for standard Helgeland-lokasjoner (Brønnøysund, Sandnessjøen, Mosjøen).
             */
            locations?:
              | {
                  name: string;
                  lat: number;
                  lng: number;
                  cameras?:
                    | {
                        url: string;
                        camTitle: string;
                        source: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'webcam';
          }
        | {
            title?: string | null;
            /**
             * La stå tomt for alle fire.
             */
            show?: ('usd' | 'eur' | 'btc' | 'brent')[] | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'currency';
          }
        | {
            title?: string | null;
            /**
             * 1–20 kommende norske helligdager.
             */
            count?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'holidays';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'places';
        value: number | Place;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'businesses';
        value: number | Business;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'press-releases';
        value: number | PressRelease;
      } | null)
    | ({
        relationTo: 'newsletters';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'ads';
        value: number | Ad;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  bio?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places_select".
 */
export interface PlacesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  municipality?: T;
  lat?: T;
  lng?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  submittedBy?: T;
  title?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  relatedBusinesses?: T;
  relatedEvents?: T;
  slug?: T;
  category?: T;
  place?: T;
  author?: T;
  tags?: T;
  featured?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses_select".
 */
export interface BusinessesSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  logo?: T;
  description?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  phone?: T;
  email?: T;
  website?: T;
  address?: T;
  city?: T;
  county?: T;
  country?: T;
  lat?: T;
  lng?: T;
  openingHours?:
    | T
    | {
        day?: T;
        opens?: T;
        closes?: T;
        id?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  submittedBy?: T;
  category?: T;
  place?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  submittedBy?: T;
  title?: T;
  image?: T;
  description?: T;
  startDate?: T;
  endDate?: T;
  locationName?: T;
  organizer?: T;
  ticketUrl?: T;
  free?: T;
  price?: T;
  slug?: T;
  category?: T;
  place?: T;
  featured?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  submittedBy?: T;
  title?: T;
  employer?: T;
  description?: T;
  jobType?: T;
  deadline?: T;
  locationName?: T;
  applicationUrl?: T;
  applicationEmail?: T;
  contactName?: T;
  contactPhone?: T;
  slug?: T;
  place?: T;
  category?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-releases_select".
 */
export interface PressReleasesSelect<T extends boolean = true> {
  title?: T;
  organization?: T;
  excerpt?: T;
  content?: T;
  image?: T;
  contactName?: T;
  contactEmail?: T;
  contactPhone?: T;
  slug?: T;
  submittedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters_select".
 */
export interface NewslettersSelect<T extends boolean = true> {
  title?: T;
  organization?: T;
  content?: T;
  image?: T;
  slug?: T;
  submittedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ads_select".
 */
export interface AdsSelect<T extends boolean = true> {
  title?: T;
  advertiser?: T;
  image?: T;
  linkUrl?: T;
  placement?: T;
  startDate?: T;
  endDate?: T;
  active?: T;
  impressions?: T;
  clicks?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              image?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        featuredPosts?:
          | T
          | {
              heading?: T;
              posts?: T;
              id?: T;
              blockName?: T;
            };
        businessList?:
          | T
          | {
              heading?: T;
              category?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        eventList?:
          | T
          | {
              heading?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              text?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              id?: T;
              blockName?: T;
            };
        powerPrices?:
          | T
          | {
              title?: T;
              zone?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        weather?:
          | T
          | {
              title?: T;
              locations?:
                | T
                | {
                    name?: T;
                    lat?: T;
                    lon?: T;
                    id?: T;
                  };
              days?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        flights?:
          | T
          | {
              title?: T;
              airports?: T;
              direction?: T;
              count?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        navJobs?:
          | T
          | {
              title?: T;
              count?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        news?:
          | T
          | {
              title?: T;
              sources?: T;
              count?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        brreg?:
          | T
          | {
              title?: T;
              count?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        webcam?:
          | T
          | {
              title?: T;
              locations?:
                | T
                | {
                    name?: T;
                    lat?: T;
                    lng?: T;
                    cameras?:
                      | T
                      | {
                          url?: T;
                          camTitle?: T;
                          source?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        currency?:
          | T
          | {
              title?: T;
              show?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        holidays?:
          | T
          | {
              title?: T;
              count?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  bio?: T;
  memberType?: T;
  approved?: T;
  sub?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  defaultSeo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  social?: {
    facebook?: string | null;
    instagram?: string | null;
    youtube?: string | null;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  eyebrow?: string | null;
  heading: string;
  subheading?: string | null;
  background?: ('color' | 'image' | 'video') | null;
  image?: (number | null) | Media;
  video?: (number | null) | Media;
  overlay?: number | null;
  ctas?:
    | {
        label: string;
        url: string;
        style?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  items?:
    | {
        label: string;
        /**
         * F.eks. /historier
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        heading?: string | null;
        links?:
          | {
              label: string;
              /**
               * F.eks. /historier
               */
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Widgets som vises i tre soner på forsiden.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sidefelt".
 */
export interface Sidefelt {
  id: number;
  /**
   * Kompakt variant. Vises i høyrespalten ved siden av innholdet på store skjermer.
   */
  sidefelt?:
    | (
        | {
            title?: string | null;
            zone?: ('NO1' | 'NO2' | 'NO3' | 'NO4' | 'NO5') | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'powerPrices';
          }
        | {
            title?: string | null;
            /**
             * La stå tomt for standard Helgeland-steder (Brønnøysund, Sandnessjøen, Mosjøen, Mo i Rana).
             */
            locations?:
              | {
                  name: string;
                  lat: number;
                  lon: number;
                  id?: string | null;
                }[]
              | null;
            /**
             * 1–7 dager.
             */
            days?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'weather';
          }
        | {
            title?: string | null;
            airports?: ('BNN' | 'SSJ' | 'MJF')[] | null;
            direction?: ('departure' | 'arrival' | 'begge') | null;
            /**
             * 1–10 avganger per flyplass.
             */
            count?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'flights';
          }
        | {
            title?: string | null;
            /**
             * 1–20 stillinger fra NAV Arbeidsplassen.
             */
            count?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'navJobs';
          }
        | {
            title?: string | null;
            /**
             * La stå tomt for alle fire kilder.
             */
            sources?: ('BAnett' | 'Helgelendingen' | 'Helgelands Blad' | 'NRK Nordland')[] | null;
            count?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'news';
          }
        | {
            title?: string | null;
            count?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'brreg';
          }
        | {
            title?: string | null;
            /**
             * La stå tomt for standard Helgeland-lokasjoner (Brønnøysund, Sandnessjøen, Mosjøen).
             */
            locations?:
              | {
                  name: string;
                  lat: number;
                  lng: number;
                  cameras?:
                    | {
                        url: string;
                        camTitle: string;
                        source: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'webcam';
          }
        | {
            title?: string | null;
            /**
             * La stå tomt for alle fire.
             */
            show?: ('usd' | 'eur' | 'btc' | 'brent')[] | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'currency';
          }
        | {
            title?: string | null;
            /**
             * 1–20 kommende norske helligdager.
             */
            count?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'holidays';
          }
      )[]
    | null;
  /**
   * Full variant. Vises mellom "Fremhevede historier" og annonsen, i et 2-kolonners grid.
   */
  midten?:
    | (
        | {
            title?: string | null;
            zone?: ('NO1' | 'NO2' | 'NO3' | 'NO4' | 'NO5') | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'powerPrices';
          }
        | {
            title?: string | null;
            /**
             * La stå tomt for standard Helgeland-steder (Brønnøysund, Sandnessjøen, Mosjøen, Mo i Rana).
             */
            locations?:
              | {
                  name: string;
                  lat: number;
                  lon: number;
                  id?: string | null;
                }[]
              | null;
            /**
             * 1–7 dager.
             */
            days?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'weather';
          }
        | {
            title?: string | null;
            airports?: ('BNN' | 'SSJ' | 'MJF')[] | null;
            direction?: ('departure' | 'arrival' | 'begge') | null;
            /**
             * 1–10 avganger per flyplass.
             */
            count?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'flights';
          }
        | {
            title?: string | null;
            /**
             * 1–20 stillinger fra NAV Arbeidsplassen.
             */
            count?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'navJobs';
          }
        | {
            title?: string | null;
            /**
             * La stå tomt for alle fire kilder.
             */
            sources?: ('BAnett' | 'Helgelendingen' | 'Helgelands Blad' | 'NRK Nordland')[] | null;
            count?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'news';
          }
        | {
            title?: string | null;
            count?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'brreg';
          }
        | {
            title?: string | null;
            /**
             * La stå tomt for standard Helgeland-lokasjoner (Brønnøysund, Sandnessjøen, Mosjøen).
             */
            locations?:
              | {
                  name: string;
                  lat: number;
                  lng: number;
                  cameras?:
                    | {
                        url: string;
                        camTitle: string;
                        source: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'webcam';
          }
        | {
            title?: string | null;
            /**
             * La stå tomt for alle fire.
             */
            show?: ('usd' | 'eur' | 'btc' | 'brent')[] | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'currency';
          }
        | {
            title?: string | null;
            /**
             * 1–20 kommende norske helligdager.
             */
            count?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'holidays';
          }
      )[]
    | null;
  /**
   * Kompakt variant. Vises som full-bredde stripe rett over footeren, i et 3-kolonners grid.
   */
  bunn?:
    | (
        | {
            title?: string | null;
            zone?: ('NO1' | 'NO2' | 'NO3' | 'NO4' | 'NO5') | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'powerPrices';
          }
        | {
            title?: string | null;
            /**
             * La stå tomt for standard Helgeland-steder (Brønnøysund, Sandnessjøen, Mosjøen, Mo i Rana).
             */
            locations?:
              | {
                  name: string;
                  lat: number;
                  lon: number;
                  id?: string | null;
                }[]
              | null;
            /**
             * 1–7 dager.
             */
            days?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'weather';
          }
        | {
            title?: string | null;
            airports?: ('BNN' | 'SSJ' | 'MJF')[] | null;
            direction?: ('departure' | 'arrival' | 'begge') | null;
            /**
             * 1–10 avganger per flyplass.
             */
            count?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'flights';
          }
        | {
            title?: string | null;
            /**
             * 1–20 stillinger fra NAV Arbeidsplassen.
             */
            count?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'navJobs';
          }
        | {
            title?: string | null;
            /**
             * La stå tomt for alle fire kilder.
             */
            sources?: ('BAnett' | 'Helgelendingen' | 'Helgelands Blad' | 'NRK Nordland')[] | null;
            count?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'news';
          }
        | {
            title?: string | null;
            count?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'brreg';
          }
        | {
            title?: string | null;
            /**
             * La stå tomt for standard Helgeland-lokasjoner (Brønnøysund, Sandnessjøen, Mosjøen).
             */
            locations?:
              | {
                  name: string;
                  lat: number;
                  lng: number;
                  cameras?:
                    | {
                        url: string;
                        camTitle: string;
                        source: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'webcam';
          }
        | {
            title?: string | null;
            /**
             * La stå tomt for alle fire.
             */
            show?: ('usd' | 'eur' | 'btc' | 'brent')[] | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'currency';
          }
        | {
            title?: string | null;
            /**
             * 1–20 kommende norske helligdager.
             */
            count?: number | null;
            variant?: ('full' | 'kompakt') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'holidays';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  defaultSeo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        youtube?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  background?: T;
  image?: T;
  video?: T;
  overlay?: T;
  ctas?:
    | T
    | {
        label?: T;
        url?: T;
        style?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sidefelt_select".
 */
export interface SidefeltSelect<T extends boolean = true> {
  sidefelt?:
    | T
    | {
        powerPrices?:
          | T
          | {
              title?: T;
              zone?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        weather?:
          | T
          | {
              title?: T;
              locations?:
                | T
                | {
                    name?: T;
                    lat?: T;
                    lon?: T;
                    id?: T;
                  };
              days?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        flights?:
          | T
          | {
              title?: T;
              airports?: T;
              direction?: T;
              count?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        navJobs?:
          | T
          | {
              title?: T;
              count?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        news?:
          | T
          | {
              title?: T;
              sources?: T;
              count?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        brreg?:
          | T
          | {
              title?: T;
              count?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        webcam?:
          | T
          | {
              title?: T;
              locations?:
                | T
                | {
                    name?: T;
                    lat?: T;
                    lng?: T;
                    cameras?:
                      | T
                      | {
                          url?: T;
                          camTitle?: T;
                          source?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        currency?:
          | T
          | {
              title?: T;
              show?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        holidays?:
          | T
          | {
              title?: T;
              count?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
      };
  midten?:
    | T
    | {
        powerPrices?:
          | T
          | {
              title?: T;
              zone?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        weather?:
          | T
          | {
              title?: T;
              locations?:
                | T
                | {
                    name?: T;
                    lat?: T;
                    lon?: T;
                    id?: T;
                  };
              days?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        flights?:
          | T
          | {
              title?: T;
              airports?: T;
              direction?: T;
              count?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        navJobs?:
          | T
          | {
              title?: T;
              count?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        news?:
          | T
          | {
              title?: T;
              sources?: T;
              count?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        brreg?:
          | T
          | {
              title?: T;
              count?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        webcam?:
          | T
          | {
              title?: T;
              locations?:
                | T
                | {
                    name?: T;
                    lat?: T;
                    lng?: T;
                    cameras?:
                      | T
                      | {
                          url?: T;
                          camTitle?: T;
                          source?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        currency?:
          | T
          | {
              title?: T;
              show?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        holidays?:
          | T
          | {
              title?: T;
              count?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
      };
  bunn?:
    | T
    | {
        powerPrices?:
          | T
          | {
              title?: T;
              zone?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        weather?:
          | T
          | {
              title?: T;
              locations?:
                | T
                | {
                    name?: T;
                    lat?: T;
                    lon?: T;
                    id?: T;
                  };
              days?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        flights?:
          | T
          | {
              title?: T;
              airports?: T;
              direction?: T;
              count?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        navJobs?:
          | T
          | {
              title?: T;
              count?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        news?:
          | T
          | {
              title?: T;
              sources?: T;
              count?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        brreg?:
          | T
          | {
              title?: T;
              count?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        webcam?:
          | T
          | {
              title?: T;
              locations?:
                | T
                | {
                    name?: T;
                    lat?: T;
                    lng?: T;
                    cameras?:
                      | T
                      | {
                          url?: T;
                          camTitle?: T;
                          source?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        currency?:
          | T
          | {
              title?: T;
              show?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        holidays?:
          | T
          | {
              title?: T;
              count?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}